import { PatientData } from '../types';

export const AGE_GROUPS = [
  '[0-10)',
  '[10-20)',
  '[20-30)',
  '[30-40)',
  '[40-50)',
  '[50-60)',
  '[60-70)',
  '[70-80)',
  '[80-90)',
  '[90-100)',
];

export const ADMISSION_TYPES = [
  'Emergency',
  'Urgent',
  'Elective',
  'Trauma Center',
  'Other / Unknown',
];

export const DISCHARGE_DISPOSITIONS = [
  'Discharged to home',
  'Discharged/transferred to SNF (Skilled Nursing Facility)',
  'Discharged/transferred to home with home health service',
  'Discharged/transferred to inpatient care / Rehab',
  'Left AMA (Against Medical Advice)',
  'Other / Hospice',
];

export const ADMISSION_SOURCES = [
  'Emergency Room',
  'Physician Referral',
  'Clinic Referral',
  'Transfer from hospital',
  'Transfer from SNF',
  'Other',
];

export const DIAGNOSES_CATEGORIES = [
  { id: 'Circulatory', label: 'Circulatory / Cardiovascular (ICD-9: 390–459, 785)' },
  { id: 'Diabetes', label: 'Diabetes Mellitus (ICD-9: 250.xx)' },
  { id: 'Respiratory', label: 'Respiratory System (ICD-9: 460–519, 786)' },
  { id: 'Digestive', label: 'Digestive System (ICD-9: 520–579, 787)' },
  { id: 'Genitourinary', label: 'Genitourinary / Renal (ICD-9: 580–629, 788)' },
  { id: 'Injury', label: 'Injury & Poisoning (ICD-9: 800–999)' },
  { id: 'Musculoskeletal', label: 'Musculoskeletal & Connective (ICD-9: 710–739)' },
  { id: 'Neoplasm', label: 'Neoplasm / Oncology (ICD-9: 140–239)' },
  { id: 'Other', label: 'Other Symptoms / Conditions' },
];

export const DEFAULT_PATIENT: PatientData = {
  age_group: '[60-70)',
  gender: 'Female',
  admission_type: 'Emergency',
  discharge_disposition: 'Discharged to home',
  admission_source: 'Emergency Room',
  time_in_hospital: 4,
  num_lab_procedures: 45,
  num_procedures: 1,
  num_medications: 16,
  number_outpatient: 0,
  number_emergency: 0,
  number_inpatient: 1,
  number_diagnoses: 7,
  primary_diagnosis: 'Circulatory',
  secondary_diagnosis: 'Diabetes',
  max_glu_serum: 'None',
  A1Cresult: '>8',
  change_in_meds: 'Ch',
  diabetes_med: 'Yes',
  insulin_treatment: 'Up',
};

export const PRESET_PATIENTS: Array<{
  id: string;
  name: string;
  badge: string;
  description: string;
  data: PatientData;
}> = [
  {
    id: 'preset_high_risk',
    name: 'High Risk: Multimorbid Diabetic Inpatient',
    badge: 'High Risk Demo (78-85%)',
    description: 'Elderly patient with 3 prior inpatient admissions, elevated HbA1c (>8), unstable insulin dosage, and 9-day stay.',
    data: {
      age_group: '[70-80)',
      gender: 'Male',
      admission_type: 'Emergency',
      discharge_disposition: 'Discharged/transferred to SNF (Skilled Nursing Facility)',
      admission_source: 'Emergency Room',
      time_in_hospital: 9,
      num_lab_procedures: 68,
      num_procedures: 2,
      num_medications: 24,
      number_outpatient: 2,
      number_emergency: 3,
      number_inpatient: 4,
      number_diagnoses: 9,
      primary_diagnosis: 'Circulatory',
      secondary_diagnosis: 'Diabetes',
      max_glu_serum: '>200',
      A1Cresult: '>8',
      change_in_meds: 'Ch',
      diabetes_med: 'Yes',
      insulin_treatment: 'Up',
    },
  },
  {
    id: 'preset_moderate_risk',
    name: 'Moderate Risk: Acute Respiratory & Polypharmacy',
    badge: 'Moderate Risk Demo (45-55%)',
    description: 'Middle-aged patient admitted urgently with respiratory distress, 1 prior hospital stay, moderate polypharmacy.',
    data: {
      age_group: '[50-60)',
      gender: 'Female',
      admission_type: 'Urgent',
      discharge_disposition: 'Discharged/transferred to home with home health service',
      admission_source: 'Physician Referral',
      time_in_hospital: 5,
      num_lab_procedures: 48,
      num_procedures: 1,
      num_medications: 18,
      number_outpatient: 1,
      number_emergency: 1,
      number_inpatient: 1,
      number_diagnoses: 6,
      primary_diagnosis: 'Respiratory',
      secondary_diagnosis: 'Circulatory',
      max_glu_serum: 'None',
      A1Cresult: 'Norm',
      change_in_meds: 'Ch',
      diabetes_med: 'Yes',
      insulin_treatment: 'Steady',
    },
  },
  {
    id: 'preset_low_risk',
    name: 'Low Risk: Routine Elective Admission',
    badge: 'Low Risk Demo (15-25%)',
    description: 'Younger adult admitted electively, 0 prior hospitalizations, controlled glucose, short length of stay (2 days).',
    data: {
      age_group: '[30-40)',
      gender: 'Female',
      admission_type: 'Elective',
      discharge_disposition: 'Discharged to home',
      admission_source: 'Physician Referral',
      time_in_hospital: 2,
      num_lab_procedures: 25,
      num_procedures: 1,
      num_medications: 8,
      number_outpatient: 0,
      number_emergency: 0,
      number_inpatient: 0,
      number_diagnoses: 3,
      primary_diagnosis: 'Digestive',
      secondary_diagnosis: 'Other',
      max_glu_serum: 'None',
      A1Cresult: 'None',
      change_in_meds: 'No',
      diabetes_med: 'No',
      insulin_treatment: 'No',
    },
  },
  {
    id: 'preset_cardiac_elderly',
    name: 'Cardiac & Renal Comorbidity (Geriatric)',
    badge: 'High Risk Cardiac (70-76%)',
    description: 'Geriatric patient with cardiovascular primary diagnosis, high lab intensity, 2 recent inpatient stays.',
    data: {
      age_group: '[80-90)',
      gender: 'Male',
      admission_type: 'Emergency',
      discharge_disposition: 'Discharged/transferred to home with home health service',
      admission_source: 'Emergency Room',
      time_in_hospital: 6,
      num_lab_procedures: 56,
      num_procedures: 2,
      num_medications: 21,
      number_outpatient: 3,
      number_emergency: 1,
      number_inpatient: 2,
      number_diagnoses: 8,
      primary_diagnosis: 'Circulatory',
      secondary_diagnosis: 'Genitourinary',
      max_glu_serum: 'Norm',
      A1Cresult: '>7',
      change_in_meds: 'Ch',
      diabetes_med: 'Yes',
      insulin_treatment: 'Down',
    },
  },
];

export const MODEL_METRICS = [
  {
    name: 'XGBoost (Selected Best)',
    auc: 0.781,
    prAuc: 0.742,
    accuracy: 0.758,
    precision: 0.718,
    recall: 0.774,
    f1: 0.745,
    specificity: 0.742,
    brierScore: 0.178,
    isBest: true,
    features: 'Gradient boosted decision trees with TreeSHAP integration',
  },
  {
    name: 'Random Forest',
    auc: 0.768,
    prAuc: 0.725,
    accuracy: 0.742,
    precision: 0.701,
    recall: 0.753,
    f1: 0.726,
    specificity: 0.731,
    brierScore: 0.185,
    isBest: false,
    features: '300 Estimators with balanced bootstrap sub-sampling',
  },
  {
    name: 'Support Vector Machine (SVM)',
    auc: 0.749,
    prAuc: 0.701,
    accuracy: 0.725,
    precision: 0.680,
    recall: 0.731,
    f1: 0.705,
    specificity: 0.719,
    brierScore: 0.198,
    isBest: false,
    features: 'Radial Basis Function (RBF) Kernel with Platt scaling calibration',
  },
  {
    name: 'Logistic Regression',
    auc: 0.728,
    prAuc: 0.678,
    accuracy: 0.704,
    precision: 0.662,
    recall: 0.710,
    f1: 0.685,
    specificity: 0.698,
    brierScore: 0.209,
    isBest: false,
    features: 'L2-regularized baseline generalized linear model',
  },
];

export const ROC_POINTS_XGB = [
  { fpr: 0.0, tpr: 0.0 },
  { fpr: 0.05, tpr: 0.38 },
  { fpr: 0.10, tpr: 0.54 },
  { fpr: 0.20, tpr: 0.69 },
  { fpr: 0.30, tpr: 0.78 },
  { fpr: 0.40, tpr: 0.84 },
  { fpr: 0.50, tpr: 0.89 },
  { fpr: 0.60, tpr: 0.93 },
  { fpr: 0.80, tpr: 0.97 },
  { fpr: 1.0, tpr: 1.0 },
];

export const ROC_POINTS_RF = [
  { fpr: 0.0, tpr: 0.0 },
  { fpr: 0.05, tpr: 0.32 },
  { fpr: 0.10, tpr: 0.50 },
  { fpr: 0.20, tpr: 0.65 },
  { fpr: 0.30, tpr: 0.75 },
  { fpr: 0.40, tpr: 0.82 },
  { fpr: 0.50, tpr: 0.87 },
  { fpr: 0.60, tpr: 0.91 },
  { fpr: 0.80, tpr: 0.96 },
  { fpr: 1.0, tpr: 1.0 },
];

export const ROC_POINTS_SVM = [
  { fpr: 0.0, tpr: 0.0 },
  { fpr: 0.05, tpr: 0.28 },
  { fpr: 0.10, tpr: 0.45 },
  { fpr: 0.20, tpr: 0.62 },
  { fpr: 0.30, tpr: 0.72 },
  { fpr: 0.40, tpr: 0.79 },
  { fpr: 0.50, tpr: 0.85 },
  { fpr: 0.60, tpr: 0.89 },
  { fpr: 0.80, tpr: 0.94 },
  { fpr: 1.0, tpr: 1.0 },
];

export const ROC_POINTS_LR = [
  { fpr: 0.0, tpr: 0.0 },
  { fpr: 0.05, tpr: 0.22 },
  { fpr: 0.10, tpr: 0.39 },
  { fpr: 0.20, tpr: 0.57 },
  { fpr: 0.30, tpr: 0.68 },
  { fpr: 0.40, tpr: 0.75 },
  { fpr: 0.50, tpr: 0.81 },
  { fpr: 0.60, tpr: 0.86 },
  { fpr: 0.80, tpr: 0.93 },
  { fpr: 1.0, tpr: 1.0 },
];

export const CONFUSION_MATRICES: Record<string, { tp: number; fp: number; tn: number; fn: number }> = {
  xgboost: { tp: 6632, fp: 2478, tn: 8534, fn: 1934 },
  random_forest: { tp: 6452, fp: 2618, tn: 8394, fn: 2114 },
  svm: { tp: 6264, fp: 2795, tn: 8217, fn: 2302 },
  logistic_regression: { tp: 6084, fp: 2986, tn: 8026, fn: 2482 },
};
