import React from 'react';
import { ShieldAlert, Info, AlertTriangle, X } from 'lucide-react';

interface ClinicalDisclaimerProps {
  compact?: boolean;
}

export const ClinicalDisclaimer: React.FC<ClinicalDisclaimerProps> = ({ compact = false }) => {
  const [dismissed, setDismissed] = React.useState(false);

  if (dismissed) return null;

  if (compact) {
    return (
      <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg px-4 py-2.5 text-xs text-amber-200 flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <ShieldAlert className="w-4 h-4 text-amber-400 shrink-0" />
          <span>
            <strong>Research & Educational Use Only:</strong> Algorithmic decision support trained on the UCI 130-US Hospitals dataset. Not intended to replace licensed medical diagnosis or clinical judgment.
          </span>
        </div>
      </div>
    );
  }

  return (
    <div className="relative bg-gradient-to-r from-amber-950/40 via-amber-900/30 to-slate-900 border border-amber-500/30 rounded-xl p-4 sm:p-5 shadow-lg backdrop-blur-sm">
      <button
        onClick={() => setDismissed(true)}
        className="absolute top-3 right-3 text-slate-400 hover:text-slate-200 p-1 rounded-md transition-colors"
        title="Dismiss notice"
      >
        <X className="w-4 h-4" />
      </button>

      <div className="flex items-start gap-3.5">
        <div className="p-2 bg-amber-500/20 text-amber-400 rounded-lg shrink-0 mt-0.5">
          <ShieldAlert className="w-5 h-5" />
        </div>
        <div className="space-y-1.5 pr-6">
          <h4 className="text-sm font-semibold text-amber-300 flex items-center gap-2">
            Clinical Decision Support & Ethical AI Disclaimer
            <span className="text-[10px] uppercase tracking-wider bg-amber-500/20 text-amber-300 px-2 py-0.5 rounded-full font-medium">
              Academic & Research System
            </span>
          </h4>
          <p className="text-xs text-slate-300 leading-relaxed">
            MedRisk AI is designed exclusively for educational, computational research, and decision-support exploration.
            The predictions and SHAP attributions generated by these machine learning models (XGBoost, Random Forest, Logistic Regression, SVM) describe probabilistic statistical associations within the historical UCI Diabetes 130-US Hospitals cohort (1999–2008).
          </p>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 pt-1 text-[11px] text-amber-200/80">
            <span className="flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-amber-400" />
              Do NOT enter real patient identifiers (PHI / MRN / PII)
            </span>
            <span className="flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-amber-400" />
              Does not replace attending physician judgment
            </span>
            <span className="flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-amber-400" />
              Thresholds are configurable research benchmarks
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
